### ISSUE TITLE
Citation information?

### ISSUE THREAD

**Issue by albertvillanova** [SpellOnYou/korean-sarcasm#2]
How could we cite your dataset?

Thank you.

**Comment by warnikchow** [comment]
Sorry for late reply. We added citation info, where the date of publishing was decided upon the period the project was done.

**Comment by albertvillanova** [comment]
Thank you. We have added it to your dataset loading script on the Hugging Face Hub: https://huggingface.co/datasets/kor_sarcasm/discussions/3
